apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  #thse labels are replicaset labels
  labels:
   project: roboshop
   tier: frontend 
   component: frontend
   version: blue
  annotations:
   kubernetes.io/change-cause: "moving to 1.29.7"

spec: 
  replicas: 4
  selector:
    matchLabels: 
      project: roboshop
      tier: frontend
      component: frontend
      version: blue
     # This is pod definition, pod is subset of replicaset
  template: 
    metadata: 
      labels: 
        project: roboshop
        tier: frontend
        component: frontend
        version: blue
    
    spec: 
      containers: 
      - name: nginx-blue
        image: satishlakamsani/blue-green:0.0.1



